kind: pipeline
type: docker
name: staking-website

steps:
  - name: build and publish image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: joinhummans/explorer:testnet
      tags: latest
